name=MPR121TouchSensor
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=MPR121 Capacitive Touch Sensor Library
paragraph=*** PRELIMINARY ***
category=Sensors
url=https://github.com/mumanchu/MPR121TouchSensor
architectures=*
